/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import pages.admin;
import services.serialservices;
import java.awt.Frame;

/**
 *
 * @author galuh
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form MainApp
     */
    public main() {

        initComponents();

        // 1. Koneksi sekali saja saat aplikasi start
        serialservices.getInstance().connect("COM3", 9600);

        // 2. Tambahkan Global Observer (misal untuk Logging)
        serialservices.getInstance().addHandler(tagId -> {
            System.out.println("Global Log: Kartu " + tagId + " terdeteksi.");
            // Jalankan fungsi database di sini
        });

        // 3. Contoh update UI di MainFrame
        serialservices.getInstance().addHandler(tagId -> {
            javax.swing.SwingUtilities.invokeLater(() -> {
                //lblStatus.setText("User Terakhir: " + tagId);
            });
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adminpage = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminpage.setText("Admin Page");
        adminpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminpageActionPerformed(evt);
            }
        });
        jPanel1.add(adminpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 71));

        jButton1.setText("Karyawan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 77, 200, 71));

        jButton2.setText("Riwayat ");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 154, 200, 71));

        jButton3.setText("Tentang");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 231, 200, 71));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminpageActionPerformed
        admin admin = new admin();
        admin.setVisible(true); 
        admin.setExtendedState(Frame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_adminpageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new main().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminpage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
